name: ğŸ§ª Build and Test

# TODO: Run a lint here too (different jobs?)

# Runs the build scripts on PR and when PR is merged to main
on:
  # TODO: Don't need to run this on push to main?
  push:
    branches:
      - main
  pull_request:
    # Only re-run job when certain files have been changed in the PR
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Run action for [home/clinic] with video [on/off] in [windows/macOS/ubuntu]
    strategy:
      matrix:
        setting: [home, clinic]
        video: [on, off]
        os: [windows-latest, macOS-latest, ubuntu-latest]
        # TODO: Remove video from matrix, add include for the video on home
        exclude:
          # Exclude video on in Ubuntu and macOS
          - os: ubuntu-latest
            setting: clinic
            video: on
          - os: ubuntu-latest
            setting: home
            video: on
          - os: macOS-latest
            setting: clinic
            video: on
          - os: macOS-latest
            setting: home
            video: on
      fail-fast: false # A failed build will not end the other matrix jobs

    steps:
      # Set up Node
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      # Install dependencies and set up environment
      - name: ğŸ“¥ Install Dependencies
        run: npm ci
      - name: ğŸ”ƒ Load .env file (.env.${{matrix.setting}})
        uses: xom9ikk/dotenv@v2
        with:
          path: ./env
          mode: ${{matrix.setting}}
      - name: ğŸ”ƒ Load .env file (.env.video)
        if: matrix.video=='on'
        uses: xom9ikk/dotenv@v2
        with:
          path: ./env
          mode: video

      # Build and test the app
      - name: âš’ Run Build
        run: npm run build
      - name: ğŸ§ª Run Test
        run: npm test
        env:
          CI: true
