# Workflow dispatch for deleting unneeded artifacts.
# Used to clear storage budget when testing release/package creation
name: Delete Artifacts Workflow
on:
  workflow_dispatch:
    inputs:
      days:
        description: Delete artifacts older than n days
        default: "5"

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: c-hive/gha-remove-artifacts@v1
        with:
          age: ${{ format('{0} days', github.event.inputs.days) }}
